(ns npu_accelerator.actor
  "npu_accelerator clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). NPU / systolic AI accelerator design.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; Npu
   {:db/ident :npu_accelerator.Npu/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :npu_accelerator.Npu/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.Npu/vendor :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.Npu/topsInt8 :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.Npu/sramMb :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.Npu/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.Npu/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; SystolicArray
   {:db/ident :npu_accelerator.SystolicArray/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :npu_accelerator.SystolicArray/npuId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.SystolicArray/rows :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.SystolicArray/columns :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.SystolicArray/dataType :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.SystolicArray/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.SystolicArray/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; MacUnit
   {:db/ident :npu_accelerator.MacUnit/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :npu_accelerator.MacUnit/arrayId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.MacUnit/precision :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.MacUnit/count :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.MacUnit/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.MacUnit/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Sram
   {:db/ident :npu_accelerator.Sram/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :npu_accelerator.Sram/npuId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.Sram/sizeMb :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.Sram/banks :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.Sram/bandwidthGbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.Sram/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.Sram/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Dataflow
   {:db/ident :npu_accelerator.Dataflow/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :npu_accelerator.Dataflow/npuId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.Dataflow/kind :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.Dataflow/reuse :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.Dataflow/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.Dataflow/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; InferenceTask
   {:db/ident :npu_accelerator.InferenceTask/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :npu_accelerator.InferenceTask/npuId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.InferenceTask/model :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.InferenceTask/batchSize :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.InferenceTask/status :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.InferenceTask/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :npu_accelerator.InferenceTask/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"Npu" "SystolicArray" "MacUnit" "Sram" "Dataflow" "InferenceTask"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "npu_accelerator: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "npu_accelerator: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "npu_accelerator: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── Npu ────────────────────────────────────────────────────────────────
(defn create-npu
  "Create a Npu."
  [port data]
  (require-fields data ["name" "vendor"])
  (let [id (new-id "npu_npu")
        e {:db/id id
           :npu_accelerator.Npu/id id
           :npu_accelerator.Npu/name (get data :name)
           :npu_accelerator.Npu/vendor (get data :vendor)
           :npu_accelerator.Npu/topsInt8 (as-double (get data :topsInt8))
           :npu_accelerator.Npu/sramMb (as-long (get data :sramMb))
           :npu_accelerator.Npu/createdAt (now)
           :npu_accelerator.Npu/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-npus
  "List Npu with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-npus port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :npu_accelerator.Npu/id))
         rows (apply-filters rows (:filter opts) [:npu_accelerator.Npu/name :npu_accelerator.Npu/vendor :npu_accelerator.Npu/topsInt8 :npu_accelerator.Npu/sramMb])]
     (paginate rows opts))))

(defn get-npu
  "Retrieve a Npu by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-npu port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-npu
  "Update a Npu; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :npu_accelerator.Npu/name (get data :name)]))
                   (cond-> (contains? data :vendor) (conj [:db/add id :npu_accelerator.Npu/vendor (get data :vendor)]))
                   (cond-> (contains? data :topsInt8) (conj [:db/add id :npu_accelerator.Npu/topsInt8 (as-double (get data :topsInt8))]))
                   (cond-> (contains? data :sramMb) (conj [:db/add id :npu_accelerator.Npu/sramMb (as-long (get data :sramMb))]))
                   (conj [:db/add id :npu_accelerator.Npu/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-npu
  "Delete a Npu."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── SystolicArray ────────────────────────────────────────────────────────────────
(defn create-systolic-array
  "Create a SystolicArray."
  [port data]
  (require-fields data ["rows" "columns"])
  (let [id (new-id "npu_sys")
        e {:db/id id
           :npu_accelerator.SystolicArray/id id
           :npu_accelerator.SystolicArray/npuId (get data :npuId)
           :npu_accelerator.SystolicArray/rows (as-long (get data :rows))
           :npu_accelerator.SystolicArray/columns (as-long (get data :columns))
           :npu_accelerator.SystolicArray/dataType (get data :dataType)
           :npu_accelerator.SystolicArray/createdAt (now)
           :npu_accelerator.SystolicArray/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-systolic-arrays
  "List SystolicArray with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-systolic-arrays port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :npu_accelerator.SystolicArray/id))
         rows (apply-filters rows (:filter opts) [:npu_accelerator.SystolicArray/npuId :npu_accelerator.SystolicArray/rows :npu_accelerator.SystolicArray/columns :npu_accelerator.SystolicArray/dataType])]
     (paginate rows opts))))

(defn get-systolic-array
  "Retrieve a SystolicArray by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-systolic-array port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :npuId) (get rec :npu_accelerator.SystolicArray/npuId))
         (assoc :npuId-obj (-pull port (get rec :npu_accelerator.SystolicArray/npuId))))))))

(defn update-systolic-array
  "Update a SystolicArray; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :npuId) (conj [:db/add id :npu_accelerator.SystolicArray/npuId (get data :npuId)]))
                   (cond-> (contains? data :rows) (conj [:db/add id :npu_accelerator.SystolicArray/rows (as-long (get data :rows))]))
                   (cond-> (contains? data :columns) (conj [:db/add id :npu_accelerator.SystolicArray/columns (as-long (get data :columns))]))
                   (cond-> (contains? data :dataType) (conj [:db/add id :npu_accelerator.SystolicArray/dataType (get data :dataType)]))
                   (conj [:db/add id :npu_accelerator.SystolicArray/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-systolic-array
  "Delete a SystolicArray."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── MacUnit ────────────────────────────────────────────────────────────────
(defn create-mac-unit
  "Create a MacUnit."
  [port data]
  (require-fields data ["precision" "count"])
  (let [id (new-id "npu_mac")
        e {:db/id id
           :npu_accelerator.MacUnit/id id
           :npu_accelerator.MacUnit/arrayId (get data :arrayId)
           :npu_accelerator.MacUnit/precision (get data :precision)
           :npu_accelerator.MacUnit/count (as-long (get data :count))
           :npu_accelerator.MacUnit/createdAt (now)
           :npu_accelerator.MacUnit/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-mac-units
  "List MacUnit with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-mac-units port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :npu_accelerator.MacUnit/id))
         rows (apply-filters rows (:filter opts) [:npu_accelerator.MacUnit/arrayId :npu_accelerator.MacUnit/precision :npu_accelerator.MacUnit/count])]
     (paginate rows opts))))

(defn get-mac-unit
  "Retrieve a MacUnit by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-mac-unit port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-mac-unit
  "Update a MacUnit; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :arrayId) (conj [:db/add id :npu_accelerator.MacUnit/arrayId (get data :arrayId)]))
                   (cond-> (contains? data :precision) (conj [:db/add id :npu_accelerator.MacUnit/precision (get data :precision)]))
                   (cond-> (contains? data :count) (conj [:db/add id :npu_accelerator.MacUnit/count (as-long (get data :count))]))
                   (conj [:db/add id :npu_accelerator.MacUnit/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-mac-unit
  "Delete a MacUnit."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Sram ────────────────────────────────────────────────────────────────
(defn create-sram
  "Create a Sram."
  [port data]
  (require-fields data ["sizeMb" "banks"])
  (let [id (new-id "npu_sra")
        e {:db/id id
           :npu_accelerator.Sram/id id
           :npu_accelerator.Sram/npuId (get data :npuId)
           :npu_accelerator.Sram/sizeMb (as-double (get data :sizeMb))
           :npu_accelerator.Sram/banks (as-long (get data :banks))
           :npu_accelerator.Sram/bandwidthGbps (as-double (get data :bandwidthGbps))
           :npu_accelerator.Sram/createdAt (now)
           :npu_accelerator.Sram/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-srams
  "List Sram with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-srams port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :npu_accelerator.Sram/id))
         rows (apply-filters rows (:filter opts) [:npu_accelerator.Sram/npuId :npu_accelerator.Sram/sizeMb :npu_accelerator.Sram/banks :npu_accelerator.Sram/bandwidthGbps])]
     (paginate rows opts))))

(defn get-sram
  "Retrieve a Sram by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-sram port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :npuId) (get rec :npu_accelerator.Sram/npuId))
         (assoc :npuId-obj (-pull port (get rec :npu_accelerator.Sram/npuId))))))))

(defn update-sram
  "Update a Sram; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :npuId) (conj [:db/add id :npu_accelerator.Sram/npuId (get data :npuId)]))
                   (cond-> (contains? data :sizeMb) (conj [:db/add id :npu_accelerator.Sram/sizeMb (as-double (get data :sizeMb))]))
                   (cond-> (contains? data :banks) (conj [:db/add id :npu_accelerator.Sram/banks (as-long (get data :banks))]))
                   (cond-> (contains? data :bandwidthGbps) (conj [:db/add id :npu_accelerator.Sram/bandwidthGbps (as-double (get data :bandwidthGbps))]))
                   (conj [:db/add id :npu_accelerator.Sram/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-sram
  "Delete a Sram."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Dataflow ────────────────────────────────────────────────────────────────
(defn create-dataflow
  "Create a Dataflow."
  [port data]
  (require-fields data ["kind" "reuse"])
  (let [id (new-id "npu_dat")
        e {:db/id id
           :npu_accelerator.Dataflow/id id
           :npu_accelerator.Dataflow/npuId (get data :npuId)
           :npu_accelerator.Dataflow/kind (get data :kind)
           :npu_accelerator.Dataflow/reuse (get data :reuse)
           :npu_accelerator.Dataflow/createdAt (now)
           :npu_accelerator.Dataflow/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-dataflows
  "List Dataflow with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-dataflows port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :npu_accelerator.Dataflow/id))
         rows (apply-filters rows (:filter opts) [:npu_accelerator.Dataflow/npuId :npu_accelerator.Dataflow/kind :npu_accelerator.Dataflow/reuse])]
     (paginate rows opts))))

(defn get-dataflow
  "Retrieve a Dataflow by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-dataflow port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :npuId) (get rec :npu_accelerator.Dataflow/npuId))
         (assoc :npuId-obj (-pull port (get rec :npu_accelerator.Dataflow/npuId))))))))

(defn update-dataflow
  "Update a Dataflow; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :npuId) (conj [:db/add id :npu_accelerator.Dataflow/npuId (get data :npuId)]))
                   (cond-> (contains? data :kind) (conj [:db/add id :npu_accelerator.Dataflow/kind (get data :kind)]))
                   (cond-> (contains? data :reuse) (conj [:db/add id :npu_accelerator.Dataflow/reuse (get data :reuse)]))
                   (conj [:db/add id :npu_accelerator.Dataflow/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-dataflow
  "Delete a Dataflow."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── InferenceTask ────────────────────────────────────────────────────────────────
(defn create-inference-task
  "Create a InferenceTask."
  [port data]
  (require-fields data ["model" "batchSize"])
  (let [id (new-id "npu_inf")
        e {:db/id id
           :npu_accelerator.InferenceTask/id id
           :npu_accelerator.InferenceTask/npuId (get data :npuId)
           :npu_accelerator.InferenceTask/model (get data :model)
           :npu_accelerator.InferenceTask/batchSize (as-long (get data :batchSize))
           :npu_accelerator.InferenceTask/status (get data :status)
           :npu_accelerator.InferenceTask/createdAt (now)
           :npu_accelerator.InferenceTask/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-inference-tasks
  "List InferenceTask with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-inference-tasks port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :npu_accelerator.InferenceTask/id))
         rows (apply-filters rows (:filter opts) [:npu_accelerator.InferenceTask/npuId :npu_accelerator.InferenceTask/model :npu_accelerator.InferenceTask/batchSize :npu_accelerator.InferenceTask/status])]
     (paginate rows opts))))

(defn get-inference-task
  "Retrieve a InferenceTask by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-inference-task port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :npuId) (get rec :npu_accelerator.InferenceTask/npuId))
         (assoc :npuId-obj (-pull port (get rec :npu_accelerator.InferenceTask/npuId))))))))

(defn update-inference-task
  "Update a InferenceTask; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :npuId) (conj [:db/add id :npu_accelerator.InferenceTask/npuId (get data :npuId)]))
                   (cond-> (contains? data :model) (conj [:db/add id :npu_accelerator.InferenceTask/model (get data :model)]))
                   (cond-> (contains? data :batchSize) (conj [:db/add id :npu_accelerator.InferenceTask/batchSize (as-long (get data :batchSize))]))
                   (cond-> (contains? data :status) (conj [:db/add id :npu_accelerator.InferenceTask/status (get data :status)]))
                   (conj [:db/add id :npu_accelerator.InferenceTask/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-inference-task
  "Delete a InferenceTask."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/npus" :op :create :entity "Npu"}
   {:method "GET" :path "/v1/npus" :op :list :entity "Npu"}
   {:method "GET" :path "/v1/npus/:id" :op :get :entity "Npu"}
   {:method "PATCH" :path "/v1/npus/:id" :op :update :entity "Npu"}
   {:method "DELETE" :path "/v1/npus/:id" :op :delete :entity "Npu"}
   {:method "POST" :path "/v1/systolicarrays" :op :create :entity "SystolicArray"}
   {:method "GET" :path "/v1/systolicarrays" :op :list :entity "SystolicArray"}
   {:method "GET" :path "/v1/systolicarrays/:id" :op :get :entity "SystolicArray"}
   {:method "PATCH" :path "/v1/systolicarrays/:id" :op :update :entity "SystolicArray"}
   {:method "DELETE" :path "/v1/systolicarrays/:id" :op :delete :entity "SystolicArray"}
   {:method "POST" :path "/v1/macunits" :op :create :entity "MacUnit"}
   {:method "GET" :path "/v1/macunits" :op :list :entity "MacUnit"}
   {:method "GET" :path "/v1/macunits/:id" :op :get :entity "MacUnit"}
   {:method "PATCH" :path "/v1/macunits/:id" :op :update :entity "MacUnit"}
   {:method "DELETE" :path "/v1/macunits/:id" :op :delete :entity "MacUnit"}
   {:method "POST" :path "/v1/srams" :op :create :entity "Sram"}
   {:method "GET" :path "/v1/srams" :op :list :entity "Sram"}
   {:method "GET" :path "/v1/srams/:id" :op :get :entity "Sram"}
   {:method "PATCH" :path "/v1/srams/:id" :op :update :entity "Sram"}
   {:method "DELETE" :path "/v1/srams/:id" :op :delete :entity "Sram"}
   {:method "POST" :path "/v1/dataflows" :op :create :entity "Dataflow"}
   {:method "GET" :path "/v1/dataflows" :op :list :entity "Dataflow"}
   {:method "GET" :path "/v1/dataflows/:id" :op :get :entity "Dataflow"}
   {:method "PATCH" :path "/v1/dataflows/:id" :op :update :entity "Dataflow"}
   {:method "DELETE" :path "/v1/dataflows/:id" :op :delete :entity "Dataflow"}
   {:method "POST" :path "/v1/inferencetasks" :op :create :entity "InferenceTask"}
   {:method "GET" :path "/v1/inferencetasks" :op :list :entity "InferenceTask"}
   {:method "GET" :path "/v1/inferencetasks/:id" :op :get :entity "InferenceTask"}
   {:method "PATCH" :path "/v1/inferencetasks/:id" :op :update :entity "InferenceTask"}
   {:method "DELETE" :path "/v1/inferencetasks/:id" :op :delete :entity "InferenceTask"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"npus" {:create create-npu :list list-npus :get get-npu :update update-npu :delete delete-npu}
   "systolicarrays" {:create create-systolic-array :list list-systolic-arrays :get get-systolic-array :update update-systolic-array :delete delete-systolic-array}
   "macunits" {:create create-mac-unit :list list-mac-units :get get-mac-unit :update update-mac-unit :delete delete-mac-unit}
   "srams" {:create create-sram :list list-srams :get get-sram :update update-sram :delete delete-sram}
   "dataflows" {:create create-dataflow :list list-dataflows :get get-dataflow :update update-dataflow :delete delete-dataflow}
   "inferencetasks" {:create create-inference-task :list list-inference-tasks :get get-inference-task :update update-inference-task :delete delete-inference-task}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "npu_accelerator-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
